INSERT INTO mobilemassages.address (userId, streetAddress, province, postCode, parkingInstructions) VALUES (1, '112C Shining Street', 'M78 Nebula', 'X3564', NULL);
INSERT INTO mobilemassages.address (userId, streetAddress, province, postCode, parkingInstructions) VALUES (2, '221B Baker Street', 'London', 15343, NULL);
INSERT INTO mobilemassages.address (userId, streetAddress, province, postCode, parkingInstructions) VALUES (3, 'VDNH', 'Moscow Metro', 49850, NULL);
INSERT INTO mobilemassages.address (userId, streetAddress, province, postCode, parkingInstructions) VALUES (4, 'Living Room in Talos', 'Unknown', 111111, NULL);
INSERT INTO mobilemassages.address (userId, streetAddress, province, postCode, parkingInstructions) VALUES (5, 'No 10 Downing Street', 'London', 99855, NULL);
INSERT INTO mobilemassages.address (userId, streetAddress, province, postCode, parkingInstructions) VALUES (6, '1-2-1101 Fengqing Street', 'Zhejiang', 33150, NULL);
INSERT INTO mobilemassages.address (userId, streetAddress, province, postCode, parkingInstructions) VALUES (7, '2-2-103 Dafu Street', 'Hunan', 33564, NULL);
INSERT INTO mobilemassages.address (userId, streetAddress, province, postCode, parkingInstructions) VALUES (8, '96A Augustus Street', 'Octavius', 88524, NULL);
INSERT INTO mobilemassages.address (userId, streetAddress, province, postCode, parkingInstructions) VALUES (9, '331C Gaius Street', 'Julius', 963422, NULL);
INSERT INTO mobilemassages.address (userId, streetAddress, province, postCode, parkingInstructions) VALUES (10, '153C Licinius Street', 'Crassus', 33221, NULL);
